# Generated by Django 4.0.6 on 2022-07-10 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='status',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='type',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='type',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('New', 'Новая'), ('In progress', 'В процессе'), ('Done', 'Выполнено')], default='New', max_length=35),
        ),
        migrations.AddField(
            model_name='type',
            name='type',
            field=models.CharField(choices=[('Task', 'Задача'), ('Bug', 'Ошибка'), ('Enhancement', 'Улучшение')], default='Task', max_length=35),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.type', verbose_name='Тип'),
        ),
        migrations.AlterModelTable(
            name='type',
            table='types',
        ),
    ]
