# Generated by Django 4.0.6 on 2022-07-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_status_created_at_remove_status_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('New', 'Новая'), ('In progress', 'В процессе'), ('Done', 'Выполнено')], default='New', max_length=35, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(choices=[('Task', 'Задача'), ('Bug', 'Ошибка'), ('Enhancement', 'Улучшение')], default='Task', max_length=35, verbose_name='Тип'),
        ),
    ]
