# Generated by Django 4.0.6 on 2022-07-11 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_status_status_alter_type_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statuses', to='webapp.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='types', to='webapp.type', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('New', 'Новая'), ('In progress', 'В процессе'), ('Done', 'Выполнено')], max_length=35),
        ),
        migrations.AlterField(
            model_name='type',
            name='type',
            field=models.CharField(choices=[('Task', 'Задача'), ('Bug', 'Ошибка'), ('Enhancement', 'Улучшение')], max_length=35),
        ),
    ]
