# Generated by Django 4.0.6 on 2022-07-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_issue_status_alter_issue_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='type',
        ),
        migrations.AddField(
            model_name='issue',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='issues', to='webapp.type'),
        ),
    ]
