# Generated by Django 4.0.6 on 2022-07-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_issue_type_issue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='issues', to='webapp.type', verbose_name='Тип'),
        ),
    ]
