# Generated by Django 4.0.6 on 2022-07-25 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_issue_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('expiration_date', models.DateField(blank=True, verbose_name='Дата окончания')),
                ('p_name', models.CharField(max_length=35, verbose_name='Название проекта')),
                ('p_description', models.TextField(max_length=3000, verbose_name='Описание проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'db_table': 'projects',
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='webapp.project', verbose_name='Проект'),
        ),
    ]
