# Generated by Django 4.0.6 on 2022-07-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_project_issue_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
    ]
