# Generated by Django 4.0.6 on 2022-08-10 18:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0009_alter_issue_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('create_project', 'Создать проект'), ('remove_project', 'Удалить проект'), ('update_project', 'Редактировать проект'), ('create_issue', 'Создать задачу'), ('delete_issue', 'Удалить задачу'), ('update_issue', 'Редактировать задачу'), ('add_user', 'Добавить пользователя'), ('delete_user', 'Удалить пользователя')], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AddField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
