# Generated by Django 4.0.6 on 2022-07-26 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_issue_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='issue',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='webapp.issue', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='webapp.project', verbose_name='Проект'),
        ),
    ]
