# Generated by Django 4.0.6 on 2022-07-26 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_project_issue_alter_issue_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='issue',
        ),
        migrations.AlterField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='webapp.project', verbose_name='Проект'),
        ),
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
    ]
