# Generated by Django 4.0.6 on 2022-07-26 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_remove_project_issue_alter_issue_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='webapp.project', verbose_name='Проект'),
        ),
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
    ]
